name: itiraf
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  fpdart: ^1.1.0
  supabase_flutter: ^2.3.4
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  dotted_border: ^2.1.0
  image_picker: ^1.0.7
  uuid: ^4.3.3
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.2.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13 
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  